### ISSUE TITLE
When checking out movies, if the user is a professor, the clerk will be prompted to look on Hummedia

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#222]

**Comment by Luke1298** [comment]
@webnard user.atributes.something should tell us rather a user is a professor or not. The only issue with that is we only have access to "user.atributes.something" if they have signed it. Is the ipad idea still possible? I can set one up easy. With the port forwarding skills taught to me by the place that shall not be named.

**Comment by trevren11** [comment]
We are keeping track of things that are on hummedia so we can just query the database to see, then we don't have to add a is_prof to the netid

**Comment by stevethomas19** [comment]
Here is my thought on how to proceed with this one:
1) Create a Modal like our alert modal but for notifications
2) Get the ldap details for the username that gets submitted [here](http://screencast.com/t/pGu6l9YO).
3) socket.emit notification if ldap details return professor

@webnard I was hoping I'd be able to do a call `var ldapDetails = yield user.ldapInfo(event.netid);` before line 28 of **core/sockets/check-out.js** but I was running into a couple of problems.
1. var ldapDetails = yield user.ldapInfo(event.netid);
SyntaxError: Unexpected strict mode reserved word yield
2. I commented out the line `'use strict';` then I got this error:
var ldapDetails = yield user.ldapInfo(event.netid);
Unexpected identifier (user)

When I console.log(user) there I get the object returned. Any suggestions on how I can get this to work?

**Comment by webnard** [comment]
The `yield` keyword only works in the context of generators. You'll have to either get the `socket.on` function to accept generators (you could use `co`, for example), or you'll have to just chain things with callbacks:

```javascript
user.ldapInfo(event.netid).then( (ldapdetails) => {
   // do something with ldapdetails
});
```

**Comment by stevethomas19** [comment]
Thank you. That worked for me. I have another question:

What is the use case behind this issue?

A professor walks in to checkout a movie upon clicking submit on [this page](http://screencast.com/t/0aFNkT4KlXH) a notification appears that says, "Oh. `user.netid` is a professor. You should check the availability of the movie on hummedia." The clerk then checks hummedia (issue #141) and if its available there tells the professor, "Actually you don't need to check this movie out because it is available online." If its not available on Hummedia then the professor is able to continue the checkout.

Is this more or less what is meant by this issue?

**Comment by stevethomas19** [comment]
This is a duplicate issue, and Harold couldn't really picture a use case where this is needed. I'm closing the issue.
