### ISSUE TITLE
Issue with checking out an item twice

### ISSUE THREAD

**Issue by trevren11** [BYU-ODH/hlrdesk#277]
Can add an item then clear the input and add the item again.

**Comment by stevethomas19** [comment]
@trevren11 I think this issue was solved. It doesn't appear to be allow a user to checkout the same item twice. http://screencast.com/t/NqcqQfsIFq1y The only thing I'd suggest is maybe displaying the alert  ("Copy " + icopy + " already selected for checkout for call " + call;) to the user.

I'm going to close this issue.
