### ISSUE TITLE
Edit Languages

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#294]
"On the 'Edit Languages' tab if you press the arrow for the drop down box it shows all the languages. The drop down box goes farther than the screen so you can't see all the languages and there is so scroll bar ability."

**Comment by stevethomas19** [comment]
Because this is a minor issue I recommend we close it. Currently datalists do not support an overflow/scroll option, but I could see it being added in the future. Alternatively we could change the datalist to a select with possible some autocomplete functionality, but that would most likely require more work than we want to put in at this time. @webnard @dcravenus Do you have any thoughts on this?

**Comment by webnard** [comment]
The only reason I vote for this to stay open is it is something that the lab attendants specifically mentioned when we initially had them run through and do a beta test for us. I know @dcravenus had been looking at some tools from Harvest (for an unrelated project) to support autocompleting a select drop down.

How quickly do you think you could drop in https://harvesthq.github.io/chosen/ and fix the issue?

**Comment by stevethomas19** [comment]
I'll look into this right now.

**Comment by trevren11** [comment]
This should be possible, though it might require some custom dropdown stuff, but jsfiddle and other places has a ton of things that would be useful

[Here](http://jsfiddle.net/vishl/gyqu8/) is a really (really) simple option with a scrolling div (not necessarily the way this should be done) as a possibility.
